<html>
  <head>
    <title>Diagnostics diff: testsWithStdLib/contracts/controlflow/flowInlining/nestedTryCatchFinally.kt</title>
    <meta charset="utf-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/github.min.css" integrity="sha512-7QTQ5Qsc/IL1k8UU2bkNFjpKTfwnvGuPYE6fzm6yeneWTEGiA3zspgjcTsSgln9m0cn3MgyE7EnDNkF1bB/uCw==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/diff2html@3.4.3/bundles/css/diff2html.min.css" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/diff2html@3.4.3/bundles/js/diff2html-ui.min.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <ul>
          <li><a id="expected" target="_blank"><strong>Expected file: </strong><span id="expected-path"></span></a></li>
          <li><a id="actual" target="_blank"><strong>Actual file: </strong><span id="actual-path"></span></a></li>
        </ul>
      </div>
      <div class="row">
        <div id="diff" style="width: 100%"></div>
      </div>
    </div>
    <script type="text/javascript">                        $('#expected').attr('href', 'https://github.com/JetBrains/Kotlin/blob/b18d4af37b58d7baa264523d3d78be7485c4884e/compiler/testData/diagnostics/testsWithStdLib/contracts/controlflow/flowInlining/nestedTryCatchFinally.kt');
                        $('#actual').attr('href', 'https://github.com/JetBrains/Kotlin/blob/b18d4af37b58d7baa264523d3d78be7485c4884e/compiler/testData/diagnostics/testsWithStdLib/contracts/controlflow/flowInlining/nestedTryCatchFinally.fir.kt');
                        $('#expected-path').text('testsWithStdLib/contracts/controlflow/flowInlining/nestedTryCatchFinally.kt');
                        $('#actual-path').text('testsWithStdLib/contracts/controlflow/flowInlining/nestedTryCatchFinally.fir.kt');

                        const diffString = `--- testsWithStdLib/contracts/controlflow/flowInlining/nestedTryCatchFinally.kt
+++ testsWithStdLib/contracts/controlflow/flowInlining/nestedTryCatchFinally.fir.kt
@@ -1,98 +1,98 @@
 // !DIAGNOSTICS: -UNUSED_PARAMETER -INVISIBLE_MEMBER -INVISIBLE_REFERENCE
 // !USE_EXPERIMENTAL: kotlin.contracts.ExperimentalContracts
 // !LANGUAGE: +AllowContractsForCustomFunctions +UseCallsInPlaceEffect
 
 import kotlin.contracts.*
 
 inline fun <T> myRun(block: () -> T): T {
     contract {
         callsInPlace(block, InvocationKind.EXACTLY_ONCE)
     }
     return block()
 }
 
 fun innerComputation(): Int = 42
 fun outerComputation(): Int = 52
 
 fun log() = Unit
 
 fun outerFinallyInitializes() {
     val x: Int
 
     try {
         myRun {
             try {
                 x = innerComputation()
             } catch (e: java.lang.Exception) {
                 log()
             }
             // possible reassignment if innerComputation finished
             <!VAL_REASSIGNMENT!>x<!> = 42
             // x is ID here
         }
 
         // Definite reassignment here, cause can get here only if myRun finished
         // Not reported because of repeating diagnostic
-        x = outerComputation()
+        <!VAL_REASSIGNMENT!>x<!> = outerComputation()
     } catch (e: java.lang.Exception) {
         // can catch exception thrown by the inner, so x can be not initialized
         <!UNINITIALIZED_VARIABLE!>x<!>.inc()
         log()
     } finally {
         // Possible reassignment (e.g. if everything finished)
         // Not reported because of repeating diagnostic
-        x = 42
+        <!VAL_REASSIGNMENT!>x<!> = 42
     }
 
     // Properly initialized
     x.inc()
 }
 
 fun innerFinallyInitializes() {
     val x: Int
     try {
         myRun {
             try {
                 innerComputation()
             } catch (e: java.lang.Exception) {
                 log()
             } finally {
                 x = 42
             }
         }
 
         // Properly initialized
         x.inc()
     } catch (e: java.lang.Exception) {
         log()
     }
 
     // Still can be unitialized because we don't know what can happen in try-block
     // (e.g., OutOfMemory exception could've happened even before myRun was executed)
     <!UNINITIALIZED_VARIABLE!>x<!>.inc()
 }
 
 
 fun innerFinallyInitializesOuterRethrows() {
     val x: Int
     try {
         myRun {
             try {
                 innerComputation()
             } catch (e: java.lang.Exception) {
                 log()
             } finally {
                 x = 42
             }
         }
 
         // Properly initialized
         x.inc()
     } catch (e: java.lang.Exception) {
         log()
         throw e
     }
 
     // Guaranteed to be initialized because all catch-clauses are rethrowing
     x.inc()
 }`;
                        const targetElement = $('#diff')[0];
                        const configuration = {
                            drawFileList: false,
                            fileListToggle: false,
                            fileListStartVisible: false,
                            fileContentToggle: false,
                            matching: 'lines',
                            outputFormat: 'side-by-side',
                            synchronisedScroll: true,
                            highlight: true,
                            renderNothingWhenEmpty: false,
                        };
                        const diff2htmlUi = new Diff2HtmlUI(targetElement, diffString, configuration);
                        diff2htmlUi.draw();
                        diff2htmlUi.highlightCode();</script>
  </body>
</html>
